### ISSUE TITLE
Support link preview in e.g. Telegram

### ISSUE THREAD

**Issue by nuclight** [leshark/nometa#3]
Целевая аудитория этой страницы запросто может не разглядеть одинокий линк и не открыть его. Соответственно, нужно добавить в <head> хотя бы минимальные <title>, og:title и og:description (см. http://ogp.me/) - думаю, хватит первой и второй строк, до перечня вопросов.

**Comment by leshark** [comment]
Использование ссылки подразумевается реплаем, из-за чего юзеру показывается уведомление. Это вряд ли остаётся незамеченным. Появление описания ссылки, на мой взгляд, просто увеличивает длину сообщения в чате и может способствовать тому, что пользователь не перейдёт на саму страницу, а ограничится чтением превью.
