### ISSUE TITLE
Добавить вторую причину

### ISSUE THREAD

**Issue by 1dNDN** [leshark/nometa#5]
Когда человек пишет метавопрос, он не только теряет время, но и может вовсе не получить ответа. 
Пример: чат на 100 человек, в сети 10, из них 5 средне разбираются в теме

Кто-то: Привет, кто умеет в python?
Пять человек: *вероятно моего уровня навыков недостаточно для того, чтобы ответить ему, лучше промолчу*

Кто-то: Привет, как в python создать переменную?
Кто-то из пяти человек: Это делается...

**Comment by leshark** [comment]
Такая ситуация возможна(как и некоторые другие, которые тоже не описаны на сайте), но ее упоминание мне кажется избыточным. Я стараюсь чтобы на сайте было минимальное кол-во текста, так как чем больше текста тем меньше людей хотят дочитать весь текст до конца.
