### ISSUE TITLE
Английский вариант?

### ISSUE THREAD

**Issue by okainov** [leshark/nometa#8]
Только что на работе хотел скинуть коллеге линк на nometa.xyz, но осознал, что английского варианта сайта не предусмотрено.

Не могли бы вы сделать английский вариант странички там же? Например, на `nometa.xyz/en` или типа того?

Нашел только nohello.com, но он несколько о другом, конкретно про "привет", в этом плане nometa куда более полезен.

**Comment by leshark** [comment]
Есть такой вариант - http://www.catb.org/esr/faqs/smart-questions.html
Где-то я вроде видел вариант покороче, но сейчас не под рукой. Если не найду в ближайшее время я подумаю над переводом.

**Comment by okainov** [comment]
Если что, некую импровизированную версию перевода выложил в #9, главное, чтобы доступно было как-то :)

**Comment by leshark** [comment]
> Если что, некую импровизированную версию перевода выложил в #9, главное, чтобы доступно было как-то :)

Нашел английский короткий вариант - https://dontasktoask.com/

**Comment by okainov** [comment]
Ну да, получше остальных, но все равно я бы предпочел просто английскую версию уже известного в русскоязычных кругах nometa.

**Comment by leshark** [comment]
Сделано в https://github.com/leshark/nometa/commit/9bb1f0aa3afb31a9843c364014bb4f96cf238bf4
